package com.plcoding.bookpedia.core.data

import com.plcoding.bookpedia.core.domain.DataError
import io.ktor.client.call.body
import io.ktor.client.statement.HttpResponse
import com.plcoding.bookpedia.core.domain.Result
import io.ktor.client.call.NoTransformationFoundException
import io.ktor.client.network.sockets.SocketTimeoutException
import io.ktor.util.network.UnresolvedAddressException
import kotlinx.coroutines.ensureActive
import kotlin.coroutines.coroutineContext

suspend inline fun <reified T> safeCall(
    execute: () -> HttpResponse
): Result<T, DataError.Remote> {
    val response = try {
        execute()
    } catch (e: SocketTimeoutException) {
        return Result.Error(DataError.Remote.TIMEOUT)
    }
    catch (e: UnresolvedAddressException){
        return Result.Error(DataError.Remote.NETWORK_ERROR)
    }
    catch (e: Exception) {
        coroutineContext.ensureActive()
        return Result.Error(DataError.Remote.UNKNOWN)
    }
    return responseResult<T>(response)
}
suspend inline fun <reified T> responseResult(
    response: HttpResponse
): Result<T, DataError.Remote> {
    return when (response.status.value) {
        in 200..299 -> try {
            val body = response.body<T>()
            Result.Success(body)
        } catch (e: NoTransformationFoundException) {
            Result.Error(DataError.Remote.SERIALIZATION_ERROR)
        }

        408 -> Result.Error(DataError.Remote.TIMEOUT)
        429 -> Result.Error(DataError.Remote.TOO_MANY_REQUESTS)
        in 500..599 -> Result.Error(DataError.Remote.SERVER_ERROR)
        else -> Result.Error(DataError.Remote.UNKNOWN)

    }

}
